---
- name: Fetch, backup, and push router configurations
  hosts: all
  tasks:
    - name: Get the current date and time
      ansible.builtin.command:
        cmd: date +%Y-%m-%d-%H:%M
      register: datetime

    - name: Fetch router configuration
      community.routeros.command:
        commands: /export
      register: router_config

    - name: Save configuration to a file
      ansible.builtin.copy:
        content: "{{ router_config.stdout }}"
        dest: "/etc/ansible/mikrotic_configs/router1_{{ datetime.stdout }}.rsc"

    - name: Git add the configuration file
      ansible.builtin.command:
        cmd: git add .
        chdir: "/etc/ansible/mikrotic_configs"

    - name: Git commit the changes
      ansible.builtin.command:
        cmd: git commit -m "Added backup configuration for router1 on {{ datetime.stdout }}"
        chdir: "/etc/ansible/mikrotic_configs"

    - name: Git push to GitHub
      ansible.builtin.command:
        cmd: git push
        chdir: "/etc/ansible/mikrotic_configs"

